version: '3.9'

services:

  votacao-db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: votacao#123321
      POSTGRES_DB: votacao
      POSTGRES_USER: votacao